spring:
	application:
		name: discovery-service

server:
	port: 8092
 
eureka:
	instance:
		hostname: localhost
	client:
		serviceUrl: 
			defaultZone: http://localhost:8092/eureka/
		register-with-eureka: false
		fetch-registry: false
